import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Management User",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div  className="bg-gradient-to-b from-[#3a7bd5] to-[#7474bf] min-h-screen">
            {children}
          </div>
      </body>
    </html>
  );
}
