import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Management User",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <div  className="bg-gradient-to-b from-[#2B32B2] to-[#1488CC] min-h-screen">
            {children}
          </div>
        </StoreProvider>  
      </body>
    </html>
  );
}
